// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const A_NIGHT_IN_TUNISIA: Standard = {
  title: 'A Night in Tunisia',
  slug: 'a-night-in-tunisia',
  composer: 'Dizzy Gillespie',
  year: 1942,
  form: 'AABA',
  defaultKey: 'D minor',
  alternateKey: 'E minor',
  tempo: { slow: 160, medium: 200, fast: 240 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['standard', 'bebop', 'gillespie', '1940s', 'latin', 'afro-cuban'],
  description: "Dizzy Gillespie's bebop classic with Afro-Cuban influences. Features the distinctive half-step harmonic movement and a challenging bebop bridge.",
  style: 'Bebop',
  historicalContext: 'Composed by Dizzy Gillespie around 1942, A Night in Tunisia blends bebop harmony with Afro-Cuban rhythmic sensibility. Its exotic Eb7→Dm vamp creates a quasi-Lydian Dominant color over a D minor tonal center, unlike anything in American jazz at the time. The tune became one of the defining compositions of the bebop era and a perennial jam session staple.',
  notableRecordings: [
    'Dizzy Gillespie — (multiple recordings from 1942 onwards)',
    'Charlie Parker — Bird and Diz (1950)',
    'Art Blakey & the Jazz Messengers — (various recordings)',
    'Dizzy Gillespie Big Band — (1940s-50s recordings)',
  ],
  harmonicSummary: 'A Night in Tunisia opens with a vamp alternating Eb7 and Dm — the Eb7 acts as a tritone substitute for A7, the dominant of D minor, creating a Lydian Dominant sound. The A section develops this Dm tonality with Latin rhythmic feel, while the bridge navigates a series of ii-V progressions in F major. The famous written-out "break" before the last A is one of the most dramatic moments in the bebop repertoire, requiring a cadenza-style solo line over the static harmony.',
  metaDescription: 'A Night in Tunisia chord changes and harmonic analysis. Dizzy Gillespie\'s bebop classic (1942): Eb7→Dm vamp, Afro-Cuban rhythms, with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 2, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 6, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Dm7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 10, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 14, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Am7b5', beats: 2 }, { symbol: 'D7b9', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Gm7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Am7b5', beats: 2 }, { symbol: 'D7b9', beats: 2 }] },
        { bar: 20, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Em7b5', beats: 2 }, { symbol: 'A7b9', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Dm7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 26, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Eb7', beats: 2 }, { symbol: 'Dm7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Am7b5', beats: 2 }, { symbol: 'D7b9', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Dm7', beats: 4 }] },
      ],
    },
  ],
};
