// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import { Standard } from '@/lib/music/types';

export const ALL_THE_THINGS_YOU_ARE: Standard = {
  title: 'All The Things You Are',
  slug: 'all-the-things-you-are',
  composer: 'Jerome Kern',
  year: 1939,
  form: 'AABA',
  defaultKey: 'Ab major',
  alternateKey: 'C major',
  tempo: {
    slow: 100,
    medium: 144,
    fast: 200,
  },
  timeSignature: '4/4',
  totalBars: 36,
  difficulty: 'intermediate',
  tags: ['standard', 'intermediate', 'ii-V-I', 'key modulation', 'Jerome Kern'],
  description: 'One of the most harmonically rich standards in the jazz repertoire, famous for its sophisticated journey through multiple key centers. The tune modulates through four different keys (Ab, C, Eb, G, E) before returning home, making it an excellent study piece for understanding key modulation and ii-V-I progressions in various tonalities.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Jerome Kern with lyrics by Oscar Hammerstein II for the 1939 Broadway musical Very Warm for May, All the Things You Are is widely considered one of the most harmonically sophisticated standards in the jazz repertoire. Its unusual 36-bar form and movement through three distinct key centers (Ab major, C major, and Eb major) challenged and delighted jazz improvisers from bebop onwards.',
  notableRecordings: [
    'Charlie Parker — (recorded multiple times)',
    'Bill Evans — Portrait in Jazz (1959)',
    'John Coltrane — (various recordings)',
    'Sonny Rollins — (various recordings)',
    'Clifford Brown & Max Roach — Study in Brown (1955)',
  ],
  harmonicSummary: 'All the Things You Are has a 36-bar AABA form (with a 4-bar coda) that cycles through three key centers. The A section establishes Ab major through a vi-ii-V-I progression (Fm7→Bbm7→Eb7→Abmaj7→Dbmaj7→G7), then the second A tonicizes C major (Cm7→Fm7→Bb7→Ebmaj7→Abmaj7→D7). The bridge resolves to G major (Gmaj7→Am7→D7) before the final A returns to Ab major. This multi-tonic structure — cycling through Ab, C, and Eb — requires improvisation across three different harmonic areas within a single chorus.',
  metaDescription: 'All the Things You Are chord changes and harmonic analysis. Jerome Kern\'s 1939 jazz standard: 36-bar form cycling through Ab major, C major, and Eb major key centers, with notation and scale guides.',
  sections: [
    {
      name: 'A1',
      label: 'A (bars 1-8)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
      ],
      analysis: {
        summary: 'Opens in Ab major with a vi-ii-V-I progression, then immediately modulates to C major via ii-V-I',
        insight: 'The opening establishes Ab as home, but bars 5-7 execute a smooth modulation up a major third to C. This is a signature move of the tune - starting on the relative minor (Fm7) creates harmonic ambiguity that makes the eventual modulation feel natural.',
        scaleGuide: [
          'Fm7: F Dorian (F G Ab Bb C D Eb)',
          'Bbm7: Bb Dorian (Bb C Db Eb F G Ab)',
          'Eb7: Eb Mixolydian (Eb F G Ab Bb C Db) or Eb Bebop Dominant',
          'Abmaj7: Ab Ionian (Ab Bb C Db Eb F G)',
          'Dbmaj7: Db Lydian (Db Eb F G Ab Bb C)',
          'Dm7: D Dorian (D E F G A B C)',
          'G7: G Mixolydian (G A B C D E F) or altered scale',
          'Cmaj7: C Ionian (C D E F G A B)',
        ],
        practiceTips: [
          'Practice the vi-ii-V-I in Ab (Fm7-Bbm7-Eb7-Abmaj7) as a unit until smooth',
          'The modulation from Ab to C happens via Dbmaj7 acting as a pivot - it\'s IV in Ab but also related to ii in C',
          'Voice lead smoothly from Dbmaj7 to Dm7 - many common tones and stepwise motion',
          'Listen to how the melody uses guide tones to make the modulation seamless',
          'Try playing the progression in both Ab and C major to understand the modulation pattern',
        ],
      },
    },
    {
      name: 'A2',
      label: 'A (bars 9-16)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
      ],
      analysis: {
        summary: 'Second A section starts with vi-ii-V-I in Eb major, then modulates to G major',
        insight: 'This section mirrors the first A section\'s structure but in a new key - we\'re now doing the same vi-ii-V-I pattern but starting in Eb (down a perfect fourth from Ab). Then it modulates to G major, continuing the pattern of modulating up a major third.',
        scaleGuide: [
          'Cm7: C Dorian (C D Eb F G A Bb)',
          'Fm7: F Dorian (F G Ab Bb C D Eb)',
          'Bb7: Bb Mixolydian (Bb C D Eb F G Ab) or Bb Bebop Dominant',
          'Ebmaj7: Eb Ionian (Eb F G Ab Bb C D)',
          'Abmaj7: Ab Lydian (Ab Bb C D Eb F G)',
          'Am7: A Dorian (A B C D E F# G)',
          'D7: D Mixolydian (D E F# G A B C) or altered scale',
          'Gmaj7: G Ionian (G A B C D E F#)',
        ],
        practiceTips: [
          'Notice the parallel structure to A1 - same harmonic rhythm, same modulation pattern',
          'Practice the vi-ii-V-I in Eb (Cm7-Fm7-Bb7-Ebmaj7) separately',
          'The Abmaj7 (bar 13) acts as a pivot chord - it\'s I in Ab but also relates to ii in G',
          'Work on smooth voice leading from Abmaj7 to Am7 - focus on chromatic motion',
          'Practice playing A1 and A2 back-to-back to internalize the key center shifts',
        ],
      },
    },
    {
      name: 'B',
      label: 'B (bars 17-24)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Emaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Emaj7', beats: 4 }] },
      ],
      analysis: {
        summary: 'Bridge features two complete ii-V-I progressions: first in G major, then in E major',
        insight: 'The bridge moves through keys by minor thirds (G to E), creating harmonic interest through symmetrical division of the octave. This section provides contrast to the A sections and reaches the furthest point harmonically from the home key of Ab.',
        scaleGuide: [
          'Am7: A Dorian (A B C D E F# G)',
          'D7: D Mixolydian (D E F# G A B C) or D Altered (D Eb F Gb Ab Bb C)',
          'Gmaj7: G Ionian (G A B C D E F#) or G Lydian',
          'F#m7: F# Dorian (F# G# A B C# D# E)',
          'B7: B Mixolydian (B C# D# E F# G# A) or B Altered (B C D Eb F G A)',
          'Emaj7: E Ionian (E F# G# A B C# D#) or E Lydian',
        ],
        practiceTips: [
          'Practice ii-V-I in G major (Am7-D7-Gmaj7) as a standalone exercise',
          'Practice ii-V-I in E major (F#m7-B7-Emaj7) separately',
          'The bridge uses a simpler, more straightforward harmonic rhythm - use this to develop melodic ideas',
          'Notice how F#m7 connects to Am7 - minor third relationship creates smooth voice leading',
          'Work on altered dominant sounds over D7 and B7 for modern jazz vocabulary',
          'The bridge is a great place to build tension before returning to the final A section',
        ],
      },
    },
    {
      name: 'A3',
      label: 'A (bars 25-36)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Dbm7', beats: 2 }, { symbol: 'Gb7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Bmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 33, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 34, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 35, chords: [{ symbol: 'Gm7b5', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 36, chords: [{ symbol: 'Fm7', beats: 4 }] },
      ],
      analysis: {
        summary: 'Final A section begins like A1 but features an extended tag ending with chromatic motion resolving back to Ab',
        insight: 'The final section creates the most sophisticated harmonic movement. After establishing Ab (bars 25-28), it uses the chromatic ii-V-I progression Dbm7-Gb7-Bmaj7 (enharmonically Cbmaj7) to move through distant keys before resolving via Bbm7-Eb7 back to Abmaj7. The final two bars (Gm7b5-C7-Fm7) are a ii-V to the relative minor, creating an open ending that can loop back to the top.',
        scaleGuide: [
          'Fm7: F Dorian (F G Ab Bb C D Eb)',
          'Bbm7: Bb Dorian (Bb C Db Eb F G Ab)',
          'Eb7: Eb Mixolydian (Eb F G Ab Bb C Db) or Eb Bebop Dominant',
          'Abmaj7: Ab Ionian (Ab Bb C Db Eb F G)',
          'Dbmaj7: Db Lydian (Db Eb F G Ab Bb C)',
          'Dbm7: Db Dorian (Db Eb Fb Gb Ab Bb Cb)',
          'Gb7: Gb Mixolydian (Gb Ab Bb Cb Db Eb Fb) or Gb Altered',
          'Bmaj7: B Ionian (B C# D# E F# G# A#) or B Lydian',
          'Gm7b5: G Locrian (G Ab Bb C Db Eb F)',
          'C7: C Altered (C Db Eb Fb Gb Ab Bb) or C Phrygian Dominant',
        ],
        practiceTips: [
          'Bars 25-29 are identical to A1 - review the voice leading practiced in the first section',
          'The chromatic tag (bars 30-31) moves through Dbm7-Gb7-Bmaj7 - practice this as a standalone ii-V-I in B',
          'Notice the smooth chromatic descent: Dbmaj7 → Dbm7 (modal mixture) → chromatically down to Bmaj7',
          'Bars 32-34 (Bbm7-Eb7-Abmaj7) bring us home - this is ii-V-I in Ab, the resolution',
          'The ending Gm7b5-C7-Fm7 is a ii-V to F minor, creating perfect loop to bar 1',
          'Practice the entire tag section (bars 29-36) slowly to master the chromatic voice leading',
          'Work on connecting Bmaj7 to Bbm7 - only a half-step but requires careful voice leading',
          'Advanced: experiment with reharmonization of the tag section while maintaining the chromatic descent',
        ],
      },
    },
  ],
};
