// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const ALONG_CAME_BETTY: Standard = {
  title: 'Along Came Betty',
  slug: 'along-came-betty',
  composer: 'Benny Golson',
  year: 1958,
  form: 'ABAB',
  defaultKey: 'Bb major',
  alternateKey: 'C major',
  tempo: { slow: 140, medium: 160, fast: 180 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['standard', 'bebop', 'hard-bop', 'complex-changes'],
  description: 'A sophisticated hard bop composition with intricate chord changes. Benny Golson\'s tribute to Betty Carter features a challenging harmonic progression that moves through multiple tonal centers, testing improvisers\' skills.',
  style: 'Hard Bop',
  historicalContext: 'Composed by Benny Golson in 1958 for the Art Blakey & the Jazz Messengers album Moanin\', Along Came Betty was written as a tribute to Betty Golson (the composer\'s wife). Its sweeping melodic arc and sophisticated multi-key harmonic movement became hallmarks of Golson\'s compositional style and made it one of the most celebrated hard bop standards.',
  notableRecordings: [
    'Art Blakey & the Jazz Messengers — Moanin\' (1958)',
    'Benny Golson — (various recordings)',
    'Hank Mobley — (various 1960s recordings)',
  ],
  harmonicSummary: 'Along Came Betty is a 32-bar AABA standard in Bb major that moves fluidly through multiple key centers via chromatic ii-V progressions. The A section begins in Bb and navigates through chromatic ii-V pairs to reach F major and back, creating a sense of harmonic journey. The bridge introduces contrasting material before the final A resolves. The tune\'s flowing harmonic rhythm and expressive melodic contour demand smooth voice leading across key centers — a hallmark of Golson\'s writing.',
  metaDescription: 'Along Came Betty chord changes and harmonic analysis. Benny Golson\'s hard bop standard (1958): multi-key ii-V progressions, AABA form, with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 6, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 9, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'F7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 19, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 20, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 21, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 22, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 23, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'F7', beats: 4 }] },
      ],
    },
  ],
};
