// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const ANTHROPOLOGY: Standard = {
  title: 'Anthropology',
  slug: 'anthropology',
  composer: 'Charlie Parker',
  year: 1946,
  form: 'AABA',
  defaultKey: 'Bb major',
  alternateKey: 'F major',
  tempo: { slow: 180, medium: 220, fast: 280 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['standard', 'bebop', 'parker', '1940s', 'rhythm-changes'],
  description: "Charlie Parker's bebop contrafact over rhythm changes. Features fast-paced bebop lines and challenging chromaticism. Built on the chord progression of \"I Got Rhythm\".",
  style: 'Bebop',
  historicalContext: 'Composed by Charlie Parker and Dizzy Gillespie in 1946, Anthropology is a bebop contrafact built on the chord changes of George Gershwin\'s "I Got Rhythm" (commonly called "Rhythm changes"). It was one of the defining compositions of the bebop era, featuring Parker\'s characteristically complex melodic lines over the rapid harmonic movement of the Rhythm changes form.',
  notableRecordings: [
    'Charlie Parker & Dizzy Gillespie — (recorded 1946)',
    'Dizzy Gillespie — Shaw \'Nuff (1945)',
    'Sonny Rollins — (multiple recordings)',
    'Thelonious Monk — (various recordings)',
  ],
  harmonicSummary: 'Anthropology uses the classic 32-bar AABA Rhythm changes form in Bb major. The A section features a I-vi-ii-V turnaround (Bbmaj7→Gm7→Cm7→F7) with a chromatic II-V-I elaboration, cycling through the circle of fifths. The bridge (B section) is a chain of dominant 7th chords moving around the circle of fifths: D7→G7→C7→F7, each lasting two bars, before returning to the A section. Mastery of this form is a rite of passage in bebop.',
  metaDescription: 'Anthropology chord changes and harmonic analysis. Charlie Parker & Dizzy Gillespie\'s bebop contrafact on Rhythm changes (1946): Bb major, AABA form, with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'F7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 29, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
  ],
};
