// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const CEORA: Standard = {
  title: 'Ceora',
  slug: 'ceora',
  composer: 'Lee Morgan',
  year: 1965,
  form: 'AABA',
  defaultKey: 'Ab major',
  alternateKey: 'G major',
  tempo: { slow: 120, medium: 140, fast: 160 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'latin', 'bossa-nova', 'modal'],
  description: 'A beautiful bossa nova with a flowing melody and modal harmony. Lee Morgan\'s composition features a sophisticated blend of Latin rhythms and modern jazz harmony, creating an accessible yet challenging piece.',
  style: 'Hard Bop',
  historicalContext: 'Composed by trumpeter Lee Morgan and recorded on his Blue Note album Cornbread (1965), Ceora is a lush, slow ballad with a bossa nova-influenced feel. Named after Morgan\'s companion Ceora, it stands out in his catalog for its tender, lyrical character — a contrast to the hard-driving bebop and hard bop for which Morgan is better known.',
  notableRecordings: [
    'Lee Morgan — Cornbread (1965)',
    'Widely recorded — (popular jazz ballad)',
  ],
  harmonicSummary: 'Ceora is an AABA standard in Ab major with a gentle bossa nova feel. The A sections feature warm major ii-V-I progressions with extended voicings (Bbm7→Eb7→Abmaj7) and some chromatic passing chords that give the tune its lush character. The bridge moves through contrasting harmonic territory before returning home. Its relatively straightforward harmonic language and song-like quality make it accessible while rewarding nuanced, lyrical playing.',
  metaDescription: 'Ceora chord changes and harmonic analysis. Lee Morgan\'s jazz ballad (1965): Ab major, AABA form, bossa nova feel, from Cornbread — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Ab7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
  ],
};
