// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const CHEROKEE: Standard = {
  title: 'Cherokee',
  slug: 'cherokee',
  composer: 'Ray Noble',
  year: 1938,
  form: 'AABA',
  defaultKey: 'Bb major',
  alternateKey: 'Ab major',
  tempo: {
    slow: 140,
    medium: 200,
    fast: 260,
  },
  timeSignature: '4/4',
  totalBars: 64,
  difficulty: 'advanced',
  tags: ['standard', 'bebop', 'advanced', 'fast tempo', 'charlie parker'],
  description:
    'Cherokee is a challenging bebop standard composed by Ray Noble in 1938 and famously recorded by Charlie Parker. This 64-bar AABA form features rapid chord changes, particularly in the bridge which moves through multiple key centers in quick succession. The tune is a rite of passage for bebop musicians and demands technical fluency and harmonic sophistication.',

  sections: [
    {
      name: 'A1',
      label: 'A Section (First)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 9, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A2',
      label: 'A Section (Second)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 19, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 25, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (Bridge)',
      bars: [
        { bar: 33, chords: [{ symbol: 'C#m7', beats: 2 }, { symbol: 'F#7', beats: 2 }] },
        { bar: 34, chords: [{ symbol: 'Bmaj7', beats: 4 }] },
        { bar: 35, chords: [{ symbol: 'Bmaj7', beats: 4 }] },
        { bar: 36, chords: [{ symbol: 'Bmaj7', beats: 4 }] },
        { bar: 37, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 38, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 39, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 40, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 41, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 42, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 43, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 44, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 45, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 46, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 47, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 48, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'A3',
      label: 'A Section (Final)',
      bars: [
        { bar: 49, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 50, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 51, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 52, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 53, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 54, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 55, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 56, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 57, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 58, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 59, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 60, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 61, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 62, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 63, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 64, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
      ],
    },
  ],
};
