// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const CORCOVADO: Standard = {
  title: 'Corcovado',
  slug: 'corcovado',
  composer: 'Antonio Carlos Jobim',
  year: 1960,
  form: 'AB',
  defaultKey: 'C major',
  alternateKey: 'F major',
  tempo: { slow: 100, medium: 130, fast: 160 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'beginner',
  tags: ['bossa-nova', 'latin', 'ballad'],
  description: 'Also known as "Quiet Nights of Quiet Stars," this gentle bossa nova ballad features simple, elegant harmonic progressions. Perfect for beginners learning jazz harmony and bossa nova feel.',
  style: 'Bossa Nova',
  historicalContext: 'Composed by Antônio Carlos Jobim and published in 1960 (also known in English as "Quiet Nights of Quiet Stars"), Corcovado takes its name from the famous Rio de Janeiro mountain surmounted by the Christ the Redeemer statue. Stan Getz and Astrud Gilberto\'s recording on Getz/Gilberto (1964) brought it to international audiences alongside "The Girl from Ipanema."',
  notableRecordings: [
    'Stan Getz & Astrud Gilberto — Getz/Gilberto (1964)',
    'Antônio Carlos Jobim — (various recordings)',
    'Widely recorded — (bossa nova ballad standard)',
  ],
  harmonicSummary: 'Corcovado is a bossa nova ballad in C major with flowing, lush harmony characteristic of Jobim\'s writing. The tune moves through major ii-V-I progressions with chromatic approach chords and extended sonorities (maj7, maj9). Jobim\'s harmonic language features unexpected chromatic ii-Vs that tonicize chords briefly before resolving — creating the characteristic "surprising but inevitable" feeling of his best work. The gentle bossa nova groove and lyrical melody reward a singing, unhurried approach.',
  metaDescription: 'Corcovado chord changes and harmonic analysis. Jobim\'s bossa nova ballad (1960): C major, chromatic ii-V progressions, from Getz/Gilberto — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-16)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 10, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 14, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (bars 17-32)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 26, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Cmaj7', beats: 2 }, { symbol: 'Dm7', beats: 1 }, { symbol: 'G7', beats: 1 }] },
      ],
    },
  ],
};
