// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import { Standard } from '@/lib/music/types';

export const FLY_ME_TO_THE_MOON: Standard = {
  title: 'Fly Me to the Moon',
  slug: 'fly-me-to-the-moon',
  composer: 'Bart Howard',
  year: 1954,
  form: 'ABAB',
  defaultKey: 'C',
  alternateKey: 'Am',
  tempo: {
    slow: 100,
    medium: 140,
    fast: 180,
  },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'beginner',
  tags: ['standard', 'beginner', 'swing', 'ii-V-I', 'circle of fourths'],
  description: 'A timeless swing standard that beautifully demonstrates the circle of fourths motion through diatonic chords.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Bm7b5', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Am7', beats: 4 }] },
      ],
      analysis: {
        summary: 'The A section establishes the circle of fourths pattern starting from Am7.',
        insight: 'This opening section moves through a complete cycle: Am7 → Dm7 → G7 → Cmaj7 → Fmaj7, demonstrating the circle of fourths motion that defines the entire tune. The section concludes with a ii-V-i in A minor (Bm7b5 → E7 → Am7), creating a perfect loop back to the beginning.',
        scaleGuide: [
          'Am7: A Dorian (A B C D E F# G)',
          'Dm7: D Dorian (D E F G A B C)',
          'G7: G Mixolydian (G A B C D E F)',
          'Cmaj7: C Ionian / C Major Scale',
          'Fmaj7: F Lydian (F G A B C D E)',
          'Bm7b5: B Locrian (B C D E F G A)',
          'E7: E Mixolydian b9 b13 or Harmonic Minor (E F# G# A B C D)',
        ],
        practiceTips: [
          'Practice the circle of fourths progression (Am-Dm-G-C-F) as a standalone exercise in all keys.',
          'Focus on voice leading: move chord tones stepwise between Am7 → Dm7 → G7 → Cmaj7.',
          'The Bm7b5 → E7 → Am7 at the end is a classic ii-V-i in A minor—practice this cadence separately.',
          'Try playing the bass line descending by fourths: A → D → G → C → F → B → E → A.',
        ],
      },
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 9, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'G7', beats: 4 }] },
        {
          bar: 15,
          chords: [
            { symbol: 'Cmaj7', beats: 2 },
            { symbol: 'Bm7b5', beats: 2 },
          ],
        },
        { bar: 16, chords: [{ symbol: 'E7', beats: 4 }] },
      ],
      analysis: {
        summary: 'The B section continues the circle of fourths pattern with a turnaround leading back to A.',
        insight: 'This section starts with a ii-V-I in C major (Dm7 → G7 → Cmaj7), then pivots with A7 as a secondary dominant (V7/ii) that leads to Dm7. The final bars (Cmaj7 → Bm7b5 → E7) set up a return to Am7, creating harmonic tension that resolves when the A section repeats.',
        scaleGuide: [
          'Dm7: D Dorian (D E F G A B C)',
          'G7: G Mixolydian (G A B C D E F)',
          'Cmaj7: C Ionian / C Major Scale',
          'A7: A Mixolydian (A B C# D E F# G) or A Lydian Dominant',
          'Bm7b5: B Locrian (B C D E F G A)',
          'E7: E Mixolydian b9 b13 or E Harmonic Minor',
        ],
        practiceTips: [
          'The A7 in bar 12 is a secondary dominant (V7 of Dm7)—practice resolving it to Dm7 with voice leading.',
          'Some versions use Am7 instead of A7 in bar 12—both work, but A7 adds more tension.',
          'Practice the turnaround progression: Cmaj7 → Bm7b5 → E7 → Am7 (resolving to the top of the form).',
          'The B section is essentially two ii-V-I progressions: Dm7-G7-Cmaj7, then Dm7-G7-Cmaj7 (with chromatic approach via Bm7b5-E7).',
        ],
      },
    },
    {
      name: 'A2',
      label: 'A Section (repeat)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Bm7b5', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Am7', beats: 4 }] },
      ],
      analysis: {
        summary: 'Identical to the first A section, reinforcing the circle of fourths motion.',
        insight: 'This repeat of the A section solidifies the harmonic pattern and gives soloists a familiar structure to navigate. The circle of fourths progression (Am → Dm → G → C → F) is now deeply established in the listener\'s ear, making it easier to anticipate chord changes and create melodic lines that flow naturally over the harmony.',
        scaleGuide: [
          'Am7: A Dorian (A B C D E F# G)',
          'Dm7: D Dorian (D E F G A B C)',
          'G7: G Mixolydian (G A B C D E F)',
          'Cmaj7: C Ionian / C Major Scale',
          'Fmaj7: F Lydian (F G A B C D E)',
          'Bm7b5: B Locrian (B C D E F G A)',
          'E7: E Mixolydian b9 b13 or Harmonic Minor',
        ],
        practiceTips: [
          'Use this repeat to experiment with variations—try different voicings or substitutions.',
          'Practice playing the same melodic phrase over both A sections, adjusting for chord tones.',
          'Focus on smooth transitions: the E7 → Am7 resolution should feel inevitable.',
          'Try alternating between shell voicings (root-7th-3rd) and full voicings to vary texture.',
        ],
      },
    },
    {
      name: 'B2',
      label: 'B Section (ending)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
      ],
      analysis: {
        summary: 'The final B section modifies the ending to resolve conclusively to Cmaj7.',
        insight: 'Instead of returning to Am7, this section resolves to Cmaj7 and holds it for two bars, creating a sense of closure. The Em7 → A7 → Dm7 → G7 progression (bars 27-30) is another circle of fourths sequence (iii-VI-ii-V), continuing the tune\'s fundamental harmonic pattern. This ending variation signals to the listener that the tune is concluding rather than looping.',
        scaleGuide: [
          'Dm7: D Dorian (D E F G A B C)',
          'G7: G Mixolydian (G A B C D E F)',
          'Em7: E Phrygian (E F G A B C D) or E Dorian',
          'A7: A Mixolydian (A B C# D E F# G)',
          'Cmaj7: C Ionian / C Major Scale',
        ],
        practiceTips: [
          'The Em7 → A7 → Dm7 → G7 sequence is a iii-VI-ii-V progression—practice this in all keys.',
          'Notice how the ending avoids the Bm7b5 → E7 turnaround from the first B section—this creates finality.',
          'Practice landing on strong chord tones (3rd, 7th, or root) of Cmaj7 in the final two bars.',
          'When soloing, use the extended Cmaj7 ending to resolve tension and bring phrases to a satisfying conclusion.',
          'Experiment with different Cmaj7 voicings in the last two bars to add color and interest.',
        ],
      },
    },
  ],
};
