// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const HERES_THAT_RAINY_DAY: Standard = {
  title: "Here's That Rainy Day",
  slug: 'heres-that-rainy-day',
  composer: 'Jimmy Van Heusen',
  year: 1953,
  form: 'AB',
  defaultKey: 'G major',
  alternateKey: 'F major',
  tempo: { slow: 60, medium: 80, fast: 100 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'ballad', 'show-tune', 'romantic', 'sophisticated'],
  description: 'A sophisticated ballad with chromatic harmonic movement. Jimmy Van Heusen\'s composition features unexpected modulations and rich chord progressions that challenge and reward improvisers with its emotional depth.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Bbdim7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'F7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 17, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Ebdim7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Bbdim7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
      ],
    },
  ],
};
