// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const HOW_INSENSITIVE: Standard = {
  title: 'How Insensitive',
  slug: 'how-insensitive',
  composer: 'Antonio Carlos Jobim',
  year: 1963,
  form: 'AB',
  defaultKey: 'D minor',
  alternateKey: 'A minor',
  tempo: { slow: 100, medium: 130, fast: 160 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'beginner',
  tags: ['bossa-nova', 'latin', 'ballad'],
  description: 'Originally "Insensatez" in Portuguese, this melancholic bossa nova ballad features a beautiful minor tonality with gentle harmonic movement. A perfect introduction to bossa nova for beginners.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-16)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Dm6', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dm6', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Bm7b5', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Em7b5', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 9, chords: [{ symbol: 'Dm6', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Dm6', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Bm7b5', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'A7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (bars 17-32)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Bm7b5', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Em7b5', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Dm6', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Em7b5', beats: 2 }, { symbol: 'A7', beats: 2 }] },
      ],
    },
  ],
};
