// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const INVITATION: Standard = {
  title: 'Invitation',
  slug: 'invitation',
  composer: 'Bronislau Kaper',
  year: 1952,
  form: 'ABAC',
  defaultKey: 'C minor',
  alternateKey: 'D minor',
  tempo: { slow: 120, medium: 160, fast: 200 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['standard', 'latin', 'ballad'],
  description: 'A sophisticated Latin-jazz standard with complex chromatic harmony and dramatic melodic contours. Features rich minor tonality and challenging voice leading.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Bronislau Kaper with lyrics by Paul Francis Webster for the 1952 film Invitation, the tune became a jazz standard through its unusual dark minor tonality and sophisticated harmonic language. Its brooding character and angular melody — quite different from typical Broadway or Hollywood standards — attracted many jazz musicians.',
  notableRecordings: [
    'Chet Baker — (various recordings)',
    'Rahsaan Roland Kirk — (various recordings)',
    'Widely recorded — (jazz standard with distinctive minor character)',
  ],
  harmonicSummary: 'Invitation is a minor-key standard (typically in C minor) with a complex, harmonically rich structure. The tune moves through the minor key with ii-V-i progressions (Dm7b5→G7→Cm) and several chromatic detours to related major key areas. The harmonic language is denser than typical American standards of the era, featuring unexpected chromatic chords that give it a more modern, even cinematic character. Its dark tonality and sophisticated changes reward careful harmonic analysis.',
  metaDescription: 'Invitation chord changes and harmonic analysis. Bronislau Kaper\'s 1952 jazz standard in C minor: minor ii-V-i progressions, chromatic harmony, with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-8)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Dm7b5', beats: 2 }, { symbol: 'G7b9', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Abmaj7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (bars 9-16)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Dm7b5', beats: 2 }, { symbol: 'G7b9', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (bars 17-24)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Dm7b5', beats: 2 }, { symbol: 'G7b9', beats: 2 }] },
        { bar: 20, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Abmaj7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
      ],
    },
    {
      name: 'C',
      label: 'C Section (bars 25-32)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'F7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Am7b5', beats: 2 }, { symbol: 'D7b9', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Dm7b5', beats: 2 }, { symbol: 'G7b9', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Cm6', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Dm7b5', beats: 2 }, { symbol: 'G7b9', beats: 2 }] },
      ],
    },
  ],
};
