// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const IT_COULD_HAPPEN_TO_YOU: Standard = {
  title: 'It Could Happen to You',
  slug: 'it-could-happen-to-you',
  composer: 'Jimmy Van Heusen',
  year: 1944,
  form: 'AABA',
  defaultKey: 'Eb major',
  alternateKey: 'F major',
  tempo: { slow: 80, medium: 120, fast: 160 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'swing', 'uptempo'],
  description: 'A swinging standard with straightforward harmony. Great for practicing ii-V-I progressions and melodic development.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Jimmy Van Heusen with lyrics by Johnny Burke for the 1944 film And the Angels Sing, It Could Happen to You became a jazz standard through its accessible harmonic language and memorable melody. It is frequently associated with Chet Baker, whose relaxed, lyrical rendition remains a touchstone interpretation.',
  notableRecordings: [
    'Bing Crosby — (1944 original film version)',
    'Chet Baker — (various recordings, considered definitive)',
    'Diana Krall — When I Look in Your Eyes (1999)',
  ],
  harmonicSummary: 'It Could Happen to You is a 32-bar AABA standard in Eb major with a warm, accessible harmonic language. The A sections feature clean ii-V-I progressions in Eb with secondary dominants adding gentle color. The bridge moves to a contrasting key area before the final A returns home. Its comfortable harmonic movement and lyrical melody make it an excellent vehicle for developing a singing, relaxed approach to jazz improvisation, particularly in a ballad or medium swing context.',
  metaDescription: 'It Could Happen to You chord changes and harmonic analysis. Jimmy Van Heusen\'s 1944 jazz standard in Eb major: AABA, clean ii-V-I — Chet Baker classic, with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 9, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Bb7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 25, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 29, chords: [{ symbol: 'Ebmaj7', beats: 2 }, { symbol: 'Cm7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
  ],
};
