// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const LUSH_LIFE: Standard = {
  title: 'Lush Life',
  slug: 'lush-life',
  composer: 'Billy Strayhorn',
  year: 1949,
  form: 'Through-composed',
  defaultKey: 'Db major',
  alternateKey: 'C major',
  tempo: { slow: 50, medium: 70, fast: 90 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['standard', 'ballad', 'strayhorn', 'complex', 'chromatic'],
  description: 'A sophisticated masterpiece by Billy Strayhorn with through-composed form. Features extensive chromaticism, modulations, and some of the most challenging harmony in the jazz repertoire.',
  style: 'Ballad',
  historicalContext: 'Composed by Billy Strayhorn between 1933 and 1938 (mostly written when he was a teenager), Lush Life is one of the most sophisticated and harmonically complex songs in the jazz repertoire. Its unusual form (not a standard 32-bar AABA), dense chromatic harmony, and deeply personal lyric about disillusionment and loneliness made it a unique masterwork. John Coltrane\'s 1957 recording is considered the definitive jazz interpretation.',
  notableRecordings: [
    'Billy Strayhorn — (original recordings)',
    'John Coltrane — Lush Life (1957, with Red Garland)',
    'Nat King Cole — (various recordings)',
    'Johnny Hartman — (various recordings)',
  ],
  harmonicSummary: 'Lush Life has an unusual form — a verse plus a 36-bar chorus — with one of the most chromatically rich harmonic progressions in the standard repertoire. The harmony moves through distant key centers via half-step and tritone relationships, with dense extended chord voicings (maj7, maj9, #11) throughout. The chorus alone passes through multiple key centers with little tonal stability, reflecting the emotional disillusionment of the lyric. It demands complete harmonic fluency and a sophisticated melodic sensibility.',
  metaDescription: 'Lush Life chord changes and harmonic analysis. Billy Strayhorn\'s complex masterpiece (1938): unusual 36-bar form, dense chromatic harmony — Coltrane classic, with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'Section A',
      bars: [
        { bar: 1, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'C#dim7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'Section B',
      bars: [
        { bar: 9, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7b9', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Abm7', beats: 2 }, { symbol: 'Db7', beats: 2 }] },
      ],
    },
    {
      name: 'C',
      label: 'Section C',
      bars: [
        { bar: 17, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 19, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'C#dim7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 23, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
      ],
    },
    {
      name: 'D',
      label: 'Section D',
      bars: [
        { bar: 25, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 29, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
      ],
    },
  ],
};
