// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const MAIDEN_VOYAGE: Standard = {
  title: 'Maiden Voyage',
  slug: 'maiden-voyage',
  composer: 'Herbie Hancock',
  year: 1965,
  form: 'AABA',
  defaultKey: 'D major',
  alternateKey: 'C major',
  tempo: { slow: 120, medium: 140, fast: 160 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'modal', 'sus-chords', 'quartal-harmony'],
  description: 'A modal jazz masterpiece built on sus chords and quartal harmony. The haunting, open sound evokes the ocean and became one of the defining compositions of 1960s modal jazz.',
  style: 'Post-Bop',
  historicalContext: 'Composed by Herbie Hancock as the title track of his 1965 Blue Note album Maiden Voyage, the tune is built entirely on suspended dominant chords (7sus4) that avoid the traditional resolution of jazz harmony. The album\'s oceanic theme — suggested by its cover art and dreamy atmosphere — influenced a generation of jazz musicians and is considered a landmark of 1960s jazz.',
  notableRecordings: [
    'Herbie Hancock — Maiden Voyage (1965)',
    'Herbie Hancock — (various live recordings)',
    'Widely covered — (jazz piano standard)',
  ],
  harmonicSummary: 'Maiden Voyage is a 16-bar form built on four suspended dominant chords (7sus4): D7sus4→F7sus4→Eb7sus4→Ab7sus4 (each lasting 4 bars). The sus4 voicings replace the 3rd with the 4th, avoiding the traditional leading-tone pull of dominant chords and creating a floating, unresolved quality. There is no tonic chord — the tune never "lands." Improvisers use the Dorian or Mixolydian modes over each chord, treating each vamp as a modal area. The oceanic harmonic atmosphere is entirely created through these four suspended colors.',
  metaDescription: 'Maiden Voyage chord changes and harmonic analysis. Herbie Hancock\'s post-bop classic (1965): four suspended 7sus4 chords, floating modal harmony — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Ebm7sus4', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Ebm7sus4', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'F#m7sus4', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'F#m7sus4', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Ebm7sus4', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Ebm7sus4', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'F#m7sus4', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'F#m7sus4', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Bbm7sus4', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Bbm7sus4', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Cm7sus4', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Cm7sus4', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Bbm7sus4', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Bbm7sus4', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Ebm7sus4', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Ebm7sus4', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Dm7sus4', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'F#m7sus4', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'F#m7sus4', beats: 4 }] },
      ],
    },
  ],
};
