// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const OLEO: Standard = {
  title: 'Oleo',
  slug: 'oleo',
  composer: 'Sonny Rollins',
  year: 1954,
  form: 'AABA',
  defaultKey: 'Bb major',
  alternateKey: 'F major',
  tempo: { slow: 180, medium: 220, fast: 280 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'bebop', 'rollins', '1950s', 'rhythm-changes'],
  description: "Sonny Rollins's bebop composition over rhythm changes. Features a memorable melody and is a favorite among jazz musicians for blowing sessions.",
  style: 'Bebop',
  historicalContext: 'Composed by Sonny Rollins and recorded in 1954 on the Miles Davis album Bags\' Groove, Oleo is a bebop contrafact built on the chord changes of George Gershwin\'s "I Got Rhythm" — making it a "Rhythm changes" tune in Bb major. Rollins\'s melodic invention over this ubiquitous form helped establish him as one of the foremost post-bop saxophonists.',
  notableRecordings: [
    'Miles Davis — Bags\' Groove (1954, with Sonny Rollins)',
    'Sonny Rollins — (various recordings)',
    'Widely played — (Rhythm changes vehicle)',
  ],
  harmonicSummary: 'Oleo uses the standard Rhythm changes form in Bb major: a 32-bar AABA with the I-vi-ii-V turnaround (Bbmaj7→Gm7→Cm7→F7) in the A sections and the cycling dominant 7th bridge (D7→G7→C7→F7). Like all Rhythm changes tunes, the A section\'s four-bar turnaround pattern and the bridge\'s four-dominant-chord cycle are the core harmonic features. At up-tempo, Oleo tests fluency in rapid ii-V-I and turnaround vocabulary. Its catchy, angular bebop melody makes it a favorite vehicle for demonstrating bebop style.',
  metaDescription: 'Oleo chord changes and harmonic analysis. Sonny Rollins\'s bebop Rhythm changes contrafact (1954): Bb major, I-vi-ii-V turnaround — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'F7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 29, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Bbmaj7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
  ],
};
