// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const ONE_NOTE_SAMBA: Standard = {
  title: 'One Note Samba',
  slug: 'one-note-samba',
  composer: 'Antonio Carlos Jobim',
  year: 1961,
  form: 'AABA',
  defaultKey: 'Bb major',
  alternateKey: 'C major',
  tempo: { slow: 130, medium: 160, fast: 200 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['bossa-nova', 'latin', 'standard'],
  description: 'Also known as "Samba de Uma Nota So," this playful Jobim composition features a repeated melody note over shifting harmonies. The A section demonstrates the bossa nova technique of constant melodic repetition with harmonic variation.',
  style: 'Bossa Nova',
  historicalContext: 'Composed by Antônio Carlos Jobim in 1959 (originally titled "Samba de Uma Nota Só"), One Note Samba is a cornerstone of the bossa nova and Brazilian jazz repertoire. Jobim\'s genius in this tune is the contrast between the static, repeated melody (hovering on a single pitch) and the richly chromatic harmonies moving beneath it — a compositional technique that influenced generations of jazz composers.',
  notableRecordings: [
    'Stan Getz & João Gilberto — Getz/Gilberto (1963)',
    'Antônio Carlos Jobim — The Composer of Desafinado Plays (1963)',
    'Ella Fitzgerald — Ella Abraça Jobim (1981)',
  ],
  harmonicSummary: 'One Note Samba features a static melody over chromatic harmonic movement, creating tension between the surface simplicity and underlying complexity. The harmony moves through a descending chromatic sequence of ii-V pairs: Bbm7→Eb7→Abmaj7, then Am7→D7→Gmaj7, then Abm7→Db7→Gbmaj7, before returning to Bb major through a ii-V-I. This chromatic descending cycle of major ii-V-Is (a half-step apart) is the tune\'s defining harmonic feature and a great vehicle for practicing ii-V patterns through non-diatonic key centers.',
  metaDescription: 'One Note Samba chord changes and harmonic analysis. Jobim\'s bossa nova classic (1959): chromatic ii-V sequence through three key centers, with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-8)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (bars 9-16)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section / Bridge (bars 17-24)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (bars 25-32)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Db7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Ebmaj7', beats: 2 }, { symbol: 'Fm7', beats: 1 }, { symbol: 'Bb7', beats: 1 }] },
      ],
    },
  ],
};
