// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const PRELUDE_TO_A_KISS: Standard = {
  title: 'Prelude to a Kiss',
  slug: 'prelude-to-a-kiss',
  composer: 'Duke Ellington',
  year: 1938,
  form: 'AABA',
  defaultKey: 'D major',
  alternateKey: 'F major',
  tempo: { slow: 50, medium: 70, fast: 90 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'ellington', 'ballad', 'romantic'],
  description: 'An Ellington masterpiece with lush chromatic harmony. Features sophisticated reharmonization and beautiful voice leading.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Duke Ellington with lyrics by Irving Gordon and Irving Mills in 1938, Prelude to a Kiss is one of Ellington\'s most harmonically adventurous compositions for a popular song. Its chromatic harmony — featuring unexpected half-step modulations and altered chords unusual for the era — gave jazz musicians a rich vehicle for sophisticated harmonic exploration.',
  notableRecordings: [
    'Duke Ellington — (1938 original)',
    'Duke Ellington & John Coltrane — (1962 collaboration)',
    'Bill Evans — (various recordings)',
    'Widely recorded — (Ellington jazz standard)',
  ],
  harmonicSummary: 'Prelude to a Kiss is an AABA standard in G major with some of the most chromatic harmonic movement in Ellington\'s catalog. The A section features unexpected half-step chord movements and altered dominants that avoid predictable ii-V-I resolution, giving the tune a searching, yearning quality that matches its title. The bridge provides harmonic contrast before the final resolution. Its unusual chromatic language makes it more challenging than it appears on the surface and rewards careful harmonic analysis.',
  metaDescription: 'Prelude to a Kiss chord changes and harmonic analysis. Duke Ellington\'s 1938 jazz standard in G major: chromatic harmony, unexpected half-step moves — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Dmaj7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 9, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Dmaj7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Bm7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'A7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 25, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Dmaj7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
      ],
    },
  ],
};
