// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const RECORDA_ME: Standard = {
  title: 'Recorda-Me',
  slug: 'recorda-me',
  composer: 'Joe Henderson',
  year: 1963,
  form: 'AB',
  defaultKey: 'A minor',
  alternateKey: 'D minor',
  tempo: { slow: 140, medium: 180, fast: 220 },
  timeSignature: '4/4',
  totalBars: 24,
  difficulty: 'intermediate',
  tags: ['hard-bop', 'modal', 'modern'],
  description: 'A classic Joe Henderson composition combining bossa nova feel with hard bop harmony. Features a 16-bar A section with modal minor tonality and an 8-bar contrasting B section.',
  style: 'Hard Bop',
  historicalContext: 'Composed by Joe Henderson and recorded on his debut Blue Note album Page One (1963) alongside Blue Bossa, Recorda-Me (meaning "Remember Me" in Portuguese) has a Latin bossa nova feel and became a standard in the hard bop and Latin jazz repertoire. Along with Blue Bossa and Ceora, it represents the Latin-influenced strand of 1960s Blue Note hard bop.',
  notableRecordings: [
    'Joe Henderson — Page One (1963)',
    'Widely recorded — (Latin jazz standard)',
  ],
  harmonicSummary: 'Recorda-Me is a minor-key Latin jazz standard (typically in A minor) with a bossa nova groove. The form moves through minor ii-V-i progressions (Bm7b5→E7→Am) and related major area harmony, with a gentle Latin rhythmic feel throughout. The harmonic language is straightforward compared to some post-bop pieces, focusing instead on the rhythmic interaction between the jazz feel and the Latin clave. Its accessible changes and appealing groove make it a popular choice for jazz sessions with a Latin flavor.',
  metaDescription: 'Recorda-Me chord changes and harmonic analysis. Joe Henderson\'s Latin jazz standard (1963): A minor, bossa nova groove — from Page One, with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-16)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Dm9', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Dm9', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7alt', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Am6', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Dm9', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Dm9', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7alt', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Am6', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section / Bridge (bars 17-24)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7alt', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Am6', beats: 4 }] },
      ],
    },
  ],
};
