// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const SONG_FOR_MY_FATHER: Standard = {
  title: 'Song for My Father',
  slug: 'song-for-my-father',
  composer: 'Horace Silver',
  year: 1964,
  form: 'AABA',
  defaultKey: 'F minor',
  alternateKey: 'E minor',
  tempo: { slow: 120, medium: 140, fast: 160 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'beginner',
  tags: ['standard', 'latin', 'bossa-nova', 'soul-jazz', 'modal'],
  description: 'A Latin-tinged soul-jazz classic with a memorable bass line. Horace Silver wrote this as a tribute to his father, incorporating Cape Verdean rhythmic influences. The simple modal structure makes it accessible for beginners.',
  style: 'Hard Bop',
  historicalContext: 'Composed by Horace Silver and recorded for the Blue Note album of the same name in 1964, Song for My Father was dedicated to Silver\'s father, John Tavares Silver, a Cape Verdean musician. Its catchy Latin groove and simple but infectious two-chord vamp became one of the most recognizable hard bop melodies. The intro was famously sampled by Steely Dan for "Rikki Don\'t Lose That Number" (1974).',
  notableRecordings: [
    'Horace Silver — Song for My Father (1964)',
    'Steely Dan — Rikki Don\'t Lose That Number (1974, sampled the intro)',
  ],
  harmonicSummary: 'Song for My Father is a minor-key Latin jazz standard in F minor built on a repeating two-chord vamp: Fm7→Eb7→Db7→C7→Fm7. This descending-bass vamp — moving in whole steps then a half step — creates the tune\'s hypnotic groove. The form alternates between this vamp and a more harmonically active "release" section with ii-V-i progressions. The simplicity of the harmonic foundation contrasts with the rhythmic sophistication of the Afro-Cuban feel, making it both accessible and groovy.',
  metaDescription: 'Song for My Father chord changes and harmonic analysis. Horace Silver\'s hard bop Latin standard (1964): F minor vamp — Steely Dan sampled it, with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Ab7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Ab7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'F7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Ab7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
      ],
    },
  ],
};
