// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const SOPHISTICATED_LADY: Standard = {
  title: 'Sophisticated Lady',
  slug: 'sophisticated-lady',
  composer: 'Duke Ellington',
  year: 1933,
  form: 'AABA',
  defaultKey: 'Ab major',
  alternateKey: 'F major',
  tempo: { slow: 60, medium: 80, fast: 100 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['standard', 'ellington', 'ballad', 'complex', 'chromatic'],
  description: 'An Ellington masterpiece with sophisticated chromatic harmony. Features extensive reharmonization and complex voice leading.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Duke Ellington in 1933 (with lyrics later added by Mitchell Parish and Irving Mills), Sophisticated Lady was one of the signature compositions of the Ellington orchestra. Ellington reportedly wrote it as a tribute to three women teachers from his childhood. Its chromatic, harmonically adventurous character and sweeping romantic quality made it a jazz standard beloved by musicians and audiences alike.',
  notableRecordings: [
    'Duke Ellington Orchestra — (1933 original)',
    'John Coltrane — (various recordings)',
    'Oscar Peterson — (various recordings)',
    'Widely recorded — (Ellington jazz standard)',
  ],
  harmonicSummary: 'Sophisticated Lady is a 32-bar AABA standard in Ab major (sometimes Db major) with one of the most chromatically rich A sections in the Ellington catalog. The A section features unexpected half-step voice movements, tritone substitutions, and a chromatic descending bass line that give the tune its distinctive "sophisticated" character. The bridge provides harmonic contrast before the final A returns home. The density of chromatic chord movement makes it more challenging than typical swing-era standards.',
  metaDescription: 'Sophisticated Lady chord changes and harmonic analysis. Duke Ellington\'s 1933 jazz standard: Ab major, chromatic descending bass, tritone substitutions — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Dbmaj7', beats: 2 }, { symbol: 'Dbm7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'F7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 9, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Dbmaj7', beats: 2 }, { symbol: 'Dbm7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'F7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 16, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 19, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Bb7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 25, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Dbmaj7', beats: 2 }, { symbol: 'Dbm7', beats: 2 }] },
        { bar: 29, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Bbm7', beats: 2 }, { symbol: 'Eb7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
      ],
    },
  ],
};
