// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const SPEAK_NO_EVIL: Standard = {
  title: 'Speak No Evil',
  slug: 'speak-no-evil',
  composer: 'Wayne Shorter',
  year: 1964,
  form: 'AB',
  defaultKey: 'C minor',
  alternateKey: 'D minor',
  tempo: { slow: 140, medium: 180, fast: 220 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'advanced',
  tags: ['hard-bop', 'modal', 'modern'],
  description: 'A challenging Wayne Shorter composition with unconventional harmonic progressions and a dark, mysterious quality. Features modal sections mixed with chromatic movement, requiring advanced harmonic understanding.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-16)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Ab7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (bars 17-32)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Cm7', beats: 4 }] },
      ],
    },
  ],
};
