// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const SPRING_IS_HERE: Standard = {
  title: 'Spring Is Here',
  slug: 'spring-is-here',
  composer: 'Richard Rodgers',
  year: 1938,
  form: 'AABA',
  defaultKey: 'Bb major',
  alternateKey: 'G major',
  tempo: { slow: 60, medium: 80, fast: 100 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'ballad', 'rodgers'],
  description: 'A bittersweet ballad by Rodgers and Hart. Features beautiful chromatic movement and rich harmonic color.',
  style: 'Ballad',
  historicalContext: 'Composed by Richard Rodgers with lyrics by Lorenz Hart for the 1938 Broadway musical I Married an Angel, Spring Is Here is a poignant ballad whose bittersweet lyric — about unrequited love despite the arrival of spring — suits its gentle, flowing harmonic language. It has been recorded by many jazz singers and instrumentalists as a vehicle for lyrical introspection.',
  notableRecordings: [
    'Chet Baker — (various recordings)',
    'Bill Evans — (various recordings)',
    'Miles Davis — (various recordings)',
  ],
  harmonicSummary: 'Spring Is Here is a 32-bar AABA ballad in F major with warm, diatonic harmonic movement. The A sections feature clean ii-V-I progressions in F with secondary dominants adding gentle color — E7 briefly tonicizing Am, A7 briefly tonicizing Dm. The bridge moves to a contrasting tonal area before the final A returns home. The tune\'s unhurried harmonic rhythm and lyrical quality make it ideal for developing a singing, breath-based approach to jazz improvisation.',
  metaDescription: 'Spring Is Here chord changes and harmonic analysis. Rodgers/Hart 1938 jazz ballad in F major: AABA, gentle ii-V-I progressions — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'Dbdim7', beats: 2 }] },
        { bar: 6, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 9, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'Dbdim7', beats: 2 }] },
        { bar: 14, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 17, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Ab7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 25, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 27, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 29, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'Dbdim7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Bbmaj7', beats: 4 }] },
      ],
    },
  ],
};
