// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const THE_SHADOW_OF_YOUR_SMILE: Standard = {
  title: 'The Shadow of Your Smile',
  slug: 'the-shadow-of-your-smile',
  composer: 'Johnny Mandel',
  year: 1965,
  form: 'AB',
  defaultKey: 'F# minor',
  alternateKey: 'E minor',
  tempo: { slow: 60, medium: 90, fast: 120 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'ballad', 'minor', 'bossa'],
  description: 'A haunting bossa nova ballad from The Sandpiper. Features beautiful chromatic voice leading and a memorable descending bass line.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'C#m7b5', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'F#7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Bm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'C#m7b5', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'F#7b9', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 17, chords: [{ symbol: 'Bm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'F#m7b5', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'B7b9', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'C#m7b5', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'F#7b9', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Bm7', beats: 2 }, { symbol: 'Em7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'C#m7b5', beats: 2 }, { symbol: 'F#7b9', beats: 2 }] },
      ],
    },
  ],
};
