// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const THE_GIRL_FROM_IPANEMA: Standard = {
  title: 'The Girl from Ipanema',
  slug: 'the-girl-from-ipanema',
  composer: 'Antonio Carlos Jobim',
  year: 1962,
  form: 'AABA',
  defaultKey: 'F major',
  alternateKey: 'Db major',
  tempo: { slow: 120, medium: 140, fast: 160 },
  timeSignature: '4/4',
  totalBars: 40,
  difficulty: 'beginner',
  tags: ['standard', 'bossa-nova', 'jobim', '1960s', 'latin'],
  description: 'Iconic bossa nova by Antonio Carlos Jobim. Features the characteristic Brazilian harmonic movement and syncopated rhythm pattern.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 11, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 17, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 21, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 33, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 34, chords: [{ symbol: 'D7b9', beats: 4 }] },
        { bar: 35, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 36, chords: [{ symbol: 'C7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 37, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 38, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 39, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 40, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
      ],
    },
  ],
};
