// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const THE_GIRL_FROM_IPANEMA: Standard = {
  title: 'The Girl from Ipanema',
  slug: 'the-girl-from-ipanema',
  composer: 'Antonio Carlos Jobim',
  year: 1962,
  form: 'AABA',
  defaultKey: 'F major',
  alternateKey: 'Db major',
  tempo: { slow: 120, medium: 140, fast: 160 },
  timeSignature: '4/4',
  totalBars: 40,
  difficulty: 'beginner',
  tags: ['standard', 'bossa-nova', 'jobim', '1960s', 'latin'],
  description: 'Iconic bossa nova by Antonio Carlos Jobim. Features the characteristic Brazilian harmonic movement and syncopated rhythm pattern.',
  style: 'Bossa Nova',
  historicalContext: 'Composed by Antônio Carlos Jobim with Portuguese lyrics by Vinícius de Moraes in 1962 (English lyrics by Norman Gimbel), The Girl from Ipanema became the second most recorded song in history after Yesterday. Stan Getz and Astrud Gilberto\'s 1964 recording won the Grammy for Record of the Year and became the defining bossa nova recording for international audiences. The tune was inspired by a young woman named Helô Pinheiro who walked past a bar where Jobim and de Moraes were sitting in Ipanema, Rio de Janeiro.',
  notableRecordings: [
    'Stan Getz & Astrud Gilberto — Getz/Gilberto (1964, Grammy winner)',
    'Antônio Carlos Jobim & Vinícius de Moraes — (original Portuguese version)',
    'Frank Sinatra & Antônio Carlos Jobim — Francis Albert Sinatra & Antônio Carlos Jobim (1967)',
  ],
  harmonicSummary: 'The Girl from Ipanema is a 32-bar AABA standard with two distinct key areas: F major (A section) and Gb major (bridge). The A section is firmly in F major with a I→IV7 progression (Fmaj7→G7→Gm7→Gb7→Fmaj7). The bridge moves to Gb major (a half-step above F) — a striking parallel modulation — with Gbmaj7→B7→F#m7→D7→Gm7→Eb7 before returning to F. The Gb major bridge (a tritone away from the home dominant) and the chromatic ii-V-I return to F are the harmonic highlights.',
  metaDescription: 'The Girl from Ipanema chord changes and harmonic analysis. Jobim\'s bossa nova classic (1962): F major with Gb major bridge — the Grammy-winning Getz/Gilberto recording, with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (repeat)',
      bars: [
        { bar: 11, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 17, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Gb7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'Bridge',
      bars: [
        { bar: 21, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Eb7', beats: 4 }] },
        { bar: 33, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 34, chords: [{ symbol: 'D7b9', beats: 4 }] },
        { bar: 35, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 36, chords: [{ symbol: 'C7', beats: 4 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (final)',
      bars: [
        { bar: 37, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 38, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 39, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 40, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
      ],
    },
  ],
};
