// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const THE_SHADOW_OF_YOUR_SMILE: Standard = {
  title: 'The Shadow of Your Smile',
  slug: 'the-shadow-of-your-smile',
  composer: 'Johnny Mandel',
  year: 1965,
  form: 'AB',
  defaultKey: 'F# minor',
  alternateKey: 'E minor',
  tempo: { slow: 60, medium: 90, fast: 120 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'ballad', 'minor', 'bossa'],
  description: 'A haunting bossa nova ballad from The Sandpiper. Features beautiful chromatic voice leading and a memorable descending bass line.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Johnny Mandel with lyrics by Paul Francis Webster for the 1965 film The Sandpiper, The Shadow of Your Smile won the Academy Award for Best Original Song. It was quickly adopted by jazz musicians for its sophisticated harmonic language and was voted the Song of the Year by ASCAP in 1965. Tony Bennett and Andy Williams recorded popular versions.',
  notableRecordings: [
    'Tony Bennett — (1965 recording)',
    'Andy Williams — (1965 recording)',
    'Bill Evans — (various recordings)',
    'Widely recorded — (Oscar-winning jazz standard)',
  ],
  harmonicSummary: 'The Shadow of Your Smile is a 32-bar AABA standard in E minor with a notably sophisticated harmonic language for a film song. The A section is in E minor, featuring minor ii-V-i progressions (F#m7b5→B7→Em) alongside chromatic passing chords that give the tune its wistful, searching quality. The bridge moves to G major (the relative major) before the final A returns to E minor. The interplay between E minor and G major gives the tune its bittersweet character.',
  metaDescription: 'The Shadow of Your Smile chord changes and harmonic analysis. Johnny Mandel\'s 1965 Oscar-winning standard in E minor: minor ii-V-i, G major bridge — with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'F#m7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'B7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Dmaj7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'C#m7b5', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'F#7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Bm7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'C#m7b5', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'F#7b9', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 17, chords: [{ symbol: 'Bm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'E7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'D7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'F#m7b5', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'B7b9', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'C#m7b5', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'F#7b9', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Bm7', beats: 2 }, { symbol: 'Em7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Am7', beats: 2 }, { symbol: 'D7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Gmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'C#m7b5', beats: 2 }, { symbol: 'F#7b9', beats: 2 }] },
      ],
    },
  ],
};
