// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const THERE_WILL_NEVER_BE_ANOTHER_YOU: Standard = {
  title: 'There Will Never Be Another You',
  slug: 'there-will-never-be-another-you',
  composer: 'Harry Warren',
  year: 1942,
  form: 'AB',
  defaultKey: 'Eb major',
  alternateKey: 'F major',
  tempo: {
    slow: 120,
    medium: 160,
    fast: 200,
  },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'swing', 'intermediate', 'ii-V-I'],
  description:
    'There Will Never Be Another You is a popular standard composed by Harry Warren in 1942. This 32-bar AB form features clear ii-V-I progressions and modulations, making it excellent for practicing bebop vocabulary and jazz improvisation. The tune moves through several key centers, providing opportunities to practice playing over key changes.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Harry Warren with lyrics by Mack Gordon for the 1942 film Iceland, There Will Never Be Another You became a jazz standard through its clean harmonic movement and bebop-friendly changes. It is one of the most called tunes at jazz jam sessions for its accessible but musically interesting ii-V-I progressions in Eb major.',
  notableRecordings: [
    'Sammy Kaye — (1942 original film version)',
    'John Coltrane — (various recordings)',
    'Bill Evans — (various recordings)',
    'Widely played — (essential jam session standard)',
  ],
  harmonicSummary: 'There Will Never Be Another You is a 32-bar ABAC standard in Eb major with clean, elegant harmonic movement. The A sections feature clear ii-V-I progressions in Eb (Fm7→Bb7→Ebmaj7) and its relative minor area, while the B and C sections provide harmonic variety. The ABAC form (as opposed to AABA) gives the tune a slightly different structural flavor. Its comfortable harmonic pacing and memorable melody make it one of the most played standards at jam sessions.',
  metaDescription: 'There Will Never Be Another You chord changes and harmonic analysis. Harry Warren\'s 1942 jazz standard in Eb major: ABAC form, clean ii-V-I — essential jam session tune, with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 4, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 10, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 12, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 14, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 15, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 17, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 20, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 21, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Gm7', beats: 2 }, { symbol: 'C7', beats: 2 }] },
        { bar: 23, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Ebm7', beats: 2 }, { symbol: 'Ab7', beats: 2 }] },
        { bar: 26, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 28, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Cm7', beats: 2 }, { symbol: 'F7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
  ],
};
