// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const WHEN_I_FALL_IN_LOVE: Standard = {
  title: 'When I Fall in Love',
  slug: 'when-i-fall-in-love',
  composer: 'Victor Young',
  year: 1952,
  form: 'AB',
  defaultKey: 'Eb major',
  alternateKey: 'C major',
  tempo: { slow: 60, medium: 80, fast: 100 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'beginner',
  tags: ['standard', 'ballad', 'young', '1950s'],
  description: 'Beautiful romantic ballad by Victor Young. Features smooth voice leading and is a perfect introduction to ballad playing.',
  style: 'Ballad',
  historicalContext: 'Composed by Victor Young with lyrics by Edward Heyman for the 1952 film One Minute to Zero, When I Fall in Love became a beloved romantic standard through recordings by Doris Day, Nat King Cole, and later Chet Baker. It was further popularized by the 1993 film Sleepless in Seattle (Céline Dion and Clive Griffin\'s version). Its simple, heartfelt character has kept it in the jazz and pop repertoire.',
  notableRecordings: [
    'Nat King Cole — (1956 recording)',
    'Doris Day — (1952 original film version)',
    'Chet Baker — (various recordings)',
    'Widely recorded — (romantic jazz ballad standard)',
  ],
  harmonicSummary: 'When I Fall in Love is a 32-bar AABA ballad in Eb major with a warm, accessible harmonic language. The A sections feature clean, diatonic ii-V-I progressions in Eb with some secondary dominants adding gentle color. The bridge moves to a contrasting tonal area (Bb major or related keys) before the final A returns home. The tune\'s straightforward harmonic movement and lyrical melody make it one of the most approachable jazz ballads for developing a singing, sustained improvisational style.',
  metaDescription: 'When I Fall in Love chord changes and harmonic analysis. Victor Young\'s 1952 jazz ballad in Eb major: AABA, warm ii-V-I progressions — Nat Cole & Chet Baker classic, with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section',
      bars: [
        { bar: 1, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section',
      bars: [
        { bar: 17, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 19, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Bb7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Ebmaj7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
      ],
    },
  ],
};
