// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const WITCH_HUNT: Standard = {
  title: 'Witch Hunt',
  slug: 'witch-hunt',
  composer: 'Wayne Shorter',
  year: 1965,
  form: 'AB',
  defaultKey: 'Eb minor',
  alternateKey: 'C minor',
  tempo: { slow: 130, medium: 160, fast: 200 },
  timeSignature: '4/4',
  totalBars: 36,
  difficulty: 'advanced',
  tags: ['hard-bop', 'modal', 'modern'],
  description: 'An advanced Wayne Shorter composition with a haunting, mysterious quality. Features an unusual 36-bar form with modal sections and dramatic harmonic shifts. The composition showcases Shorter\'s gift for creating atmosphere through harmony.',
  style: 'Post-Bop',
  historicalContext: 'Composed by Wayne Shorter and recorded on the Miles Davis Quintet album E.S.P. (1965), Witch Hunt exemplifies the "new thing" direction of the mid-1960s Davis Quintet — open, post-bop harmonic language with a minor-key modal feel. Shorter\'s compositions for the second great Miles Davis Quintet were characterized by their dark atmosphere and ambiguous harmonic centers.',
  notableRecordings: [
    'Miles Davis Quintet — E.S.P. (1965)',
    'Wayne Shorter — (various recordings)',
  ],
  harmonicSummary: 'Witch Hunt is a minor-key composition in C minor with Wayne Shorter\'s characteristic post-bop harmonic language — suspended chords, ambiguous tonal centers, and non-functional progressions that create atmosphere rather than direct the ear through traditional ii-V-i resolution. The form alternates between static minor chord areas and more harmonically active passages. Improvising over it requires sensitivity to color and atmosphere rather than rapid chord-scale pattern execution.',
  metaDescription: 'Witch Hunt chord changes and harmonic analysis. Wayne Shorter\'s post-bop composition (1965): C minor, suspended modal harmony — Miles Davis Quintet E.S.P., with notation and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-18)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 3, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 5, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 6, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 7, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 8, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 9, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Gbmaj7', beats: 4 }] },
        { bar: 11, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Fm7', beats: 4 }] },
        { bar: 13, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 17, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Ebm7', beats: 4 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (bars 19-36)',
      bars: [
        { bar: 19, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Dbmaj7', beats: 4 }] },
        { bar: 21, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 22, chords: [{ symbol: 'Cm7', beats: 4 }] },
        { bar: 23, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 24, chords: [{ symbol: 'Bbm7', beats: 4 }] },
        { bar: 25, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'Abmaj7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 30, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 31, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 32, chords: [{ symbol: 'Abm7', beats: 4 }] },
        { bar: 33, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 34, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 35, chords: [{ symbol: 'Ebm7', beats: 4 }] },
        { bar: 36, chords: [{ symbol: 'Ebm7', beats: 4 }] },
      ],
    },
  ],
};
