// NOTE: Only chord progressions, analysis, and practice tips. NO melody or lyrics (copyrighted).

import type { Standard } from '@/lib/music/types';

export const YOU_STEPPED_OUT_OF_A_DREAM: Standard = {
  title: 'You Stepped Out of a Dream',
  slug: 'you-stepped-out-of-a-dream',
  composer: 'Nacio Herb Brown',
  year: 1940,
  form: 'ABAC',
  defaultKey: 'C major',
  alternateKey: 'Eb major',
  tempo: { slow: 120, medium: 160, fast: 200 },
  timeSignature: '4/4',
  totalBars: 32,
  difficulty: 'intermediate',
  tags: ['standard', 'ballad', 'swing'],
  description: 'A romantic ballad with chromatically descending bass lines and rich harmonic colors. Features extended ii-V progressions and smooth voice leading.',
  style: 'Jazz Standard',
  historicalContext: 'Composed by Nacio Herb Brown with lyrics by Gus Kahn for the 1940 MGM film Ziegfeld Girl, You Stepped Out of a Dream has a flowing, dreamlike character well suited to jazz interpretation. It became a jazz standard through recordings by various jazz musicians who appreciated its elegant harmonic movement and memorable melody.',
  notableRecordings: [
    'Tony Martin — (1941 original film version)',
    'John Coltrane — (various recordings)',
    'Oscar Peterson — (various recordings)',
    'Widely recorded — (jazz standard)',
  ],
  harmonicSummary: 'You Stepped Out of a Dream is a 32-bar AABA standard in C major with smooth, flowing harmonic movement. The A sections feature clear ii-V-I progressions in C major with secondary dominants adding color — the harmony moves with a dreamlike, effortless quality. The bridge provides harmonic contrast through a brief modulation before the final A resolves home. The tune\'s comfortable harmonic pacing and lyrical melody suit medium swing tempos and ballad treatments equally well.',
  metaDescription: 'You Stepped Out of a Dream chord changes and harmonic analysis. Nacio Herb Brown\'s 1940 jazz standard in C major: AABA, flowing ii-V-I — with notation, playback, and scale guides.',
  sections: [
    {
      name: 'A',
      label: 'A Section (bars 1-8)',
      bars: [
        { bar: 1, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 2, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7', beats: 2 }] },
        { bar: 3, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 4, chords: [{ symbol: 'Abm7', beats: 2 }, { symbol: 'Db7', beats: 2 }] },
        { bar: 5, chords: [{ symbol: 'Cmaj7', beats: 2 }, { symbol: 'Am7', beats: 2 }] },
        { bar: 6, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 7, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 8, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
      ],
    },
    {
      name: 'B',
      label: 'B Section (bars 9-16)',
      bars: [
        { bar: 9, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 10, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7', beats: 2 }] },
        { bar: 11, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 12, chords: [{ symbol: 'Abm7', beats: 2 }, { symbol: 'Db7', beats: 2 }] },
        { bar: 13, chords: [{ symbol: 'Gm7', beats: 4 }] },
        { bar: 14, chords: [{ symbol: 'C7', beats: 4 }] },
        { bar: 15, chords: [{ symbol: 'Fmaj7', beats: 4 }] },
        { bar: 16, chords: [{ symbol: 'Fm7', beats: 2 }, { symbol: 'Bb7', beats: 2 }] },
      ],
    },
    {
      name: 'A',
      label: 'A Section (bars 17-24)',
      bars: [
        { bar: 17, chords: [{ symbol: 'Cmaj7', beats: 4 }] },
        { bar: 18, chords: [{ symbol: 'Bm7b5', beats: 2 }, { symbol: 'E7', beats: 2 }] },
        { bar: 19, chords: [{ symbol: 'Am7', beats: 4 }] },
        { bar: 20, chords: [{ symbol: 'Abm7', beats: 2 }, { symbol: 'Db7', beats: 2 }] },
        { bar: 21, chords: [{ symbol: 'Cmaj7', beats: 2 }, { symbol: 'Am7', beats: 2 }] },
        { bar: 22, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 23, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 24, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
      ],
    },
    {
      name: 'C',
      label: 'C Section (bars 25-32)',
      bars: [
        { bar: 25, chords: [{ symbol: 'Em7', beats: 4 }] },
        { bar: 26, chords: [{ symbol: 'A7', beats: 4 }] },
        { bar: 27, chords: [{ symbol: 'Dm7', beats: 4 }] },
        { bar: 28, chords: [{ symbol: 'G7', beats: 4 }] },
        { bar: 29, chords: [{ symbol: 'Em7', beats: 2 }, { symbol: 'A7', beats: 2 }] },
        { bar: 30, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
        { bar: 31, chords: [{ symbol: 'Cmaj7', beats: 2 }, { symbol: 'Am7', beats: 2 }] },
        { bar: 32, chords: [{ symbol: 'Dm7', beats: 2 }, { symbol: 'G7', beats: 2 }] },
      ],
    },
  ],
};
